### PR TITLE
styled the buttons and organized the structure of the table and layou…

### PR DESCRIPTION
**Pull request by DavidA123777**
styled the buttons and organized the structure of the table and layout of the design. Included active and hover styles for the buttons. Added box shadows to improve the loom of the table.

### CODE REVIEW

**Review by Kazi27 — APPROVED** [review]
Looks better than before for sure!

**Comment by Rahatk1** [comment]
nice

**Comment by George-Sucuzhanay** [comment]
Note: 
As part of this pull request the PR concerning grid expansion is resolved. 👍 Great work David!

**Comment by Kazi27** [comment]
Ohh so we already completed expand endless extra credit criteria? Awesome.

**Pull request merged**
