### PR TITLE
added a color dropdown menu on site

### PR DESCRIPTION
**Pull request by George-Sucuzhanay**
Added a color dropdown menu on site

### CODE REVIEW

**Comment by George-Sucuzhanay** [comment]
My import to App.js is being pushed shortly.

**Comment by George-Sucuzhanay** [comment]
Working on implementing a colorwheel instead of a color dropdown. Standby.

**Comment by Kazi27** [comment]
Sounds good George!

**Review by Kazi27 — APPROVED** [review]
The color picker is placed and implemented properly! Awesome fr

**Review by Rahatk1 — APPROVED** [review]
Ok, Looks good. I will start cooking up in fill all and remove all.

**Pull request merged**
