### PR TITLE
Remove col works

### PR DESCRIPTION
**Pull request by Kazi27**
I tried to implement remove col in a similar fashion but used slice instead which just gets rid of the rightmost cell from each row so basically a column:

https://github.com/Rahatk1/ReactGRIDMAKER/assets/90419249/9713f97d-411a-4811-b155-040ea475ee90

### CODE REVIEW

**Comment by Kazi27** [comment]
I was testing this out and discovered an edge case where when you add rows and the delete the column so the last column, add row doesn't work anymore. BUT when you hit add col, all the rows (the ones you deleted + the ones you tried to add but didn't add) show up. I attached a video to illustrate the issue, I'll work on solving it today


https://github.com/Rahatk1/ReactGRIDMAKER/assets/90419249/93fd9cd7-e3a0-4f8b-b68e-4fdf26af2643

**Review by Rahatk1 — APPROVED** [review]
ok

**Comment by Kazi27** [comment]
BOYS. I DONE DID IT. IT TOOK 2 HOURS BUT I GET REACT NOW (somewhat, I think). To fix the issue I

1. Modified Davids addRow with an if/else statement handling the case when there are rows or no rows
2. Updated removeRow to use slice instead of the spread operator
3. Added removeCol to use a spread operator and slice because it wouldn't function other than that
4. Also fixed the edge case by adding an if/else statement where when there is only one column left to delete before returning to an empty grid, you just update the state to be the empty grid which gives the effect of removing the last row anyways. 

I also cleaned up the comments and made the App.js file less messy than before if you guys want to understand what the code does. Other than that, this is how it looks like for me and everything works with each other right now so lmk if it does for u too:

https://github.com/Rahatk1/ReactGRIDMAKER/assets/90419249/2eb836db-38d7-4c23-9fbc-925c9d07a61f

**Review by George-Sucuzhanay — APPROVED** [review]
Great work Kazi! Remove column works as intended! Your continued updates on the PR is appreciated.

**Pull request merged**
