### PR TITLE
Created a selectColor handler function to retrieve value from colorwheel

### PR DESCRIPTION
**Pull request by George-Sucuzhanay**
Create a selectColor handler function to retrieve value from colorwheel

Testing:

1. Ensure that the colorwheel values are console logging as you move your mouse in the colorwheel

### CODE REVIEW

**Comment by George-Sucuzhanay** [comment]
Ensure to remove console log prior to initializing the implementation of fillAll and similar funcs

**Review by Kazi27 — APPROVED** [review]
Looks good!

**Review by Rahatk1 — APPROVED** [review]
Nice work

**Comment by George-Sucuzhanay** [comment]
selectColor is probably not a great name now that I think about it. Perhaps retrieveColor is better.

**Pull request merged**
