### PR TITLE
Remove color

### PR DESCRIPTION
**Pull request by Rahatk1**
Added button to remove all color from cells, but merge conflict prolly bc i createed branch from another branch and not main/ @Kazi27 if you have time l8r cook

### CODE REVIEW

**Comment by Kazi27** [comment]
I'll check it out

**Comment by Rahatk1** [comment]
looks good

**Comment by Kazi27** [comment]
RemoveColor works on my end, I'll see if I can resolve the conflict

**Review by Kazi27 — APPROVED** [review]
Yeah I resolved the conflicts but now that removeColor is implemented, fill uncolor doesn't work like when you try to fill uncolor a cell that you removed color from, it doesn't work. I'll make a separate branch to try and fix that but right now there's no issue with remove col so we can merge

**Pull request merged**
